---
- name: Run Docker Compose
  hosts: all
  become: true
  remote_user: ubuntu

  tasks:
  - name: Change directory
    command: cd /home/ubuntu/docker-compose-linux/

  - name: Run docker compose
    command: sudo docker-compose up -d